/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.views.despesas;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import src.models.Despesa;
import src.models.Pessoa;
import src.services.DataManager;
import src.utils.Constantes;

/**
 *
 * @author Ricardo Alves
 */
public final class CalcularValor extends javax.swing.JPanel {

    DataManager<Despesa> dmDespesa = null;
    DataManager<Pessoa> dmPessoa = null;
    private DefaultTableModel model = null;

    public final void initDataManager() {
        try {
            dmDespesa = new DataManager<>(Despesa.class.getName(), Constantes.DIRETORIO_FILE, true, "despesas");
            dmPessoa = new DataManager<>(Pessoa.class.getName(), Constantes.DIRETORIO_FILE + Constantes.NOME_BASE_FILE_USUARIOS);
        } catch (Exception e) {
            System.out.println("Erro ao iniciar o data manager!" + e.getMessage());
        }

    }

    public final void initAno() {
        dmDespesa.getDataManagerList().forEach(item -> {
            String newItem = item.getCodigo().substring(2, 6);
            int itemCount = jComboBox_ano.getItemCount();
            boolean canAdd = true;
            for (int i = 0; i < itemCount; i++) { // Valida se a opção já existe 
                String itemCombo = jComboBox_ano.getItemAt(i);
                if (newItem.equalsIgnoreCase(itemCombo)) {
                    canAdd = false;
                }
            }
            if (canAdd) {
                this.jComboBox_ano.addItem(newItem);
            }
        });
    }

    public Object[] orderColums(Object[] values) {
        Object[] retArray = new Object[7];
        String codigo = values[0].toString();
        String mes = codigo.substring(0, 2);
        String ano = codigo.substring(2, 6);
        retArray[0] = values[0];
        retArray[1] = values[1];
        retArray[2] = values[2];
        retArray[3] = values[3];
        retArray[4] = values[4];
        retArray[5] = mes + "/" + ano;
        retArray[6] = values[5];
        return retArray;
    }

    private void refreshTable() {
        model.setRowCount(0);

        try {
            dmDespesa = new DataManager<>(Despesa.class.getName(), Constantes.DIRETORIO_FILE, true, "despesas");
            dmDespesa.getDataManagerList().forEach(despesa -> {
                model.addRow(orderColums(despesa.getValues()));
            });
        } catch (Exception ex) {
            Logger.getLogger(Despesas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public CalcularValor() {
        initComponents();
        this.model = (DefaultTableModel) jTable_despesas.getModel();
        initDataManager();
        initAno();
        refreshTable();
        applyFilters();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_despesas = new javax.swing.JTable();
        jPanel_inputs = new javax.swing.JPanel();
        jLabel_totalRendimentos = new javax.swing.JLabel();
        jTextField_valor = new javax.swing.JTextField();
        jLabel_totalRendimentos1 = new javax.swing.JLabel();
        jComboBox_prioridade = new javax.swing.JComboBox<>();
        jComboBox_ano = new javax.swing.JComboBox<>();
        jLabel_mesReseva = new javax.swing.JLabel();
        calcular = new javax.swing.JButton();
        jComboBox_mes = new javax.swing.JComboBox<>();
        jLabel_mesReseva1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMaximumSize(new java.awt.Dimension(670, 440));
        jPanel1.setMinimumSize(new java.awt.Dimension(670, 440));

        jTable_despesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nome", "Descrição", "Categoria", "Prioridade", "Data", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_despesas.getTableHeader().setReorderingAllowed(false);
        jTable_despesas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable_despesasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable_despesasFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_despesas);

        jPanel_inputs.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_inputs.setMinimumSize(new java.awt.Dimension(670, 80));
        jPanel_inputs.setPreferredSize(new java.awt.Dimension(670, 80));
        jPanel_inputs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_totalRendimentos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_totalRendimentos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_totalRendimentos.setText("Tipo:");
        jPanel_inputs.add(jLabel_totalRendimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, 30));

        jTextField_valor.setEditable(false);
        jPanel_inputs.add(jTextField_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 70, 30));

        jLabel_totalRendimentos1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_totalRendimentos1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_totalRendimentos1.setText("Valor:");
        jPanel_inputs.add(jLabel_totalRendimentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 50, 30));

        jComboBox_prioridade.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jComboBox_prioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        jPanel_inputs.add(jComboBox_prioridade, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 90, 30));

        jComboBox_ano.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jComboBox_ano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBox_ano.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_anoItemStateChanged(evt);
            }
        });
        jComboBox_ano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_anoActionPerformed(evt);
            }
        });
        jPanel_inputs.add(jComboBox_ano, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 90, 30));

        jLabel_mesReseva.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_mesReseva.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mesReseva.setText("Ano:");
        jPanel_inputs.add(jLabel_mesReseva, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 30));

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        jPanel_inputs.add(calcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, 80, 30));

        jComboBox_mes.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jComboBox_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jComboBox_mes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_mesItemStateChanged(evt);
            }
        });
        jPanel_inputs.add(jComboBox_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 90, 30));

        jLabel_mesReseva1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_mesReseva1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_mesReseva1.setText("Mês");
        jPanel_inputs.add(jLabel_mesReseva1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 30));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_inputs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel_inputs, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_despesasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable_despesasFocusGained
    }//GEN-LAST:event_jTable_despesasFocusGained

    private void jTable_despesasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable_despesasFocusLost
    }//GEN-LAST:event_jTable_despesasFocusLost

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        int[] rows = jTable_despesas.getSelectedRows();
        float total = 0;
        for (int i = 0; i < rows.length; i++) {
            int row = rows[i];
            float value = (float) model.getValueAt(row, 6); // Pega o valor da linha
            total += value;
        }

        total = total / dmPessoa.getDataManagerList().size();
        this.jTextField_valor.setText(total + "");

    }//GEN-LAST:event_calcularActionPerformed

    private void jComboBox_anoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_anoActionPerformed

    }//GEN-LAST:event_jComboBox_anoActionPerformed

    private void jComboBox_anoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_anoItemStateChanged
        applyFilters();
    }//GEN-LAST:event_jComboBox_anoItemStateChanged

    private void jComboBox_mesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_mesItemStateChanged
        applyFilters();
    }//GEN-LAST:event_jComboBox_mesItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcular;
    private javax.swing.JComboBox<String> jComboBox_ano;
    private javax.swing.JComboBox<String> jComboBox_mes;
    private javax.swing.JComboBox<String> jComboBox_prioridade;
    private javax.swing.JLabel jLabel_mesReseva;
    private javax.swing.JLabel jLabel_mesReseva1;
    private javax.swing.JLabel jLabel_totalRendimentos;
    private javax.swing.JLabel jLabel_totalRendimentos1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_inputs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_despesas;
    private javax.swing.JTextField jTextField_valor;
    // End of variables declaration//GEN-END:variables

    public String searchValue() {
        String value = (String) jComboBox_ano.getSelectedItem();
        String valueMes = (String) jComboBox_mes.getSelectedItem();
        String search = "";
        String[] meses = {"Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro"};

        if (valueMes.equalsIgnoreCase(meses[0])) {
            search = "01" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[1])) {
            search = "02" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[2])) {
            search = "03" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[3])) {
            search = "04" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[4])) {
            search = "05" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[5])) {
            search = "06" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[6])) {
            search = "07" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[7])) {
            search = "08" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[8])) {
            search = "09" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[9])) {
            search = "10" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[10])) {
            search = "11" + value;
        }
        if (valueMes.equalsIgnoreCase(meses[11])) {
            search = "12" + value;
        }

        return search;

    }

    public void applyFilters() {
        String search = searchValue();
        model.setRowCount(0);
        dmDespesa.getIfContains(search).forEach((item) -> {
            Despesa d = new Despesa(item);
            model.addRow(orderColums(d.getValues()));
        });
    }
}
