/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src.views.despesas;

import javax.swing.table.DefaultTableModel;
/**
 *
 * @author wilson
 */
public class Despesas extends javax.swing.JPanel {

    private DefaultTableModel model = null;

    public Despesas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_alunos = new javax.swing.JTable();
        jPanel_inputs = new javax.swing.JPanel();
        jTextField_nome = new javax.swing.JTextField();
        jLabel_nome = new javax.swing.JLabel();
        jLabel_email = new javax.swing.JLabel();
        jTextField_rendimentos = new javax.swing.JTextField();
        jLabel_totalRendimentos = new javax.swing.JLabel();
        jLabel_codAluno = new javax.swing.JLabel();
        jTextField_codAluno = new javax.swing.JTextField();
        jTextField_email1 = new javax.swing.JTextField();
        jTextField_rendimentos1 = new javax.swing.JTextField();
        jLabel_totalRendimentos1 = new javax.swing.JLabel();
        jPanel_acoes = new javax.swing.JPanel();
        jButton_novo = new javax.swing.JButton();
        jButton_editar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jButton_atualizar = new javax.swing.JButton();
        jTextField_pesquisar = new javax.swing.JTextField();
        jButton_pesquisar = new javax.swing.JButton();
        jButton_salvar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 0, 51));
        setMaximumSize(new java.awt.Dimension(670, 440));
        setMinimumSize(new java.awt.Dimension(670, 440));
        setPreferredSize(new java.awt.Dimension(670, 440));

        jTable_alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Descrição", "Categoria", "Prioridade", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable_alunos.getTableHeader().setReorderingAllowed(false);
        jTable_alunos.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                jTable_alunosHierarchyChanged(evt);
            }
        });
        jTable_alunos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTable_alunosFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTable_alunosFocusLost(evt);
            }
        });
        jTable_alunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_alunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_alunos);

        jPanel_inputs.setBackground(new java.awt.Color(51, 51, 51));
        jPanel_inputs.setMinimumSize(new java.awt.Dimension(670, 80));
        jPanel_inputs.setPreferredSize(new java.awt.Dimension(670, 80));
        jPanel_inputs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel_inputs.add(jTextField_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 10, 240, 30));

        jLabel_nome.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_nome.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_nome.setText("Nome:");
        jPanel_inputs.add(jLabel_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 30));

        jLabel_email.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_email.setText("Descrição:");
        jPanel_inputs.add(jLabel_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 10, 80, 30));

        jTextField_rendimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rendimentosActionPerformed(evt);
            }
        });
        jPanel_inputs.add(jTextField_rendimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 130, 30));

        jLabel_totalRendimentos.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_totalRendimentos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_totalRendimentos.setText("Prioridade:");
        jPanel_inputs.add(jLabel_totalRendimentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 90, 30));

        jLabel_codAluno.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_codAluno.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_codAluno.setText("Categoria:");
        jPanel_inputs.add(jLabel_codAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, 30));

        jTextField_codAluno.setEnabled(false);
        jPanel_inputs.add(jTextField_codAluno, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 130, 30));
        jPanel_inputs.add(jTextField_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 180, 30));

        jTextField_rendimentos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_rendimentos1ActionPerformed(evt);
            }
        });
        jPanel_inputs.add(jTextField_rendimentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 80, 30));

        jLabel_totalRendimentos1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel_totalRendimentos1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_totalRendimentos1.setText("Valor:");
        jPanel_inputs.add(jLabel_totalRendimentos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 50, 30));

        jButton_novo.setText("Novo");
        jButton_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_novoActionPerformed(evt);
            }
        });

        jButton_editar.setText("Editar");
        jButton_editar.setEnabled(false);

        jButton_Excluir.setText("Excluir");
        jButton_Excluir.setEnabled(false);
        jButton_Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_ExcluirMouseClicked(evt);
            }
        });

        jButton_atualizar.setText("Aualizar");
        jButton_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_atualizarActionPerformed(evt);
            }
        });

        jTextField_pesquisar.setToolTipText("Digite o nome");

        jButton_pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/images/icons8-pesquisar-15.png"))); // NOI18N
        jButton_pesquisar.setToolTipText("Buscar por nome");
        jButton_pesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_pesquisarMouseClicked(evt);
            }
        });

        jButton_salvar.setText("Salvar");
        jButton_salvar.setEnabled(false);
        jButton_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_acoesLayout = new javax.swing.GroupLayout(jPanel_acoes);
        jPanel_acoes.setLayout(jPanel_acoesLayout);
        jPanel_acoesLayout.setHorizontalGroup(
            jPanel_acoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_acoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_novo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_editar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Excluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel_acoesLayout.setVerticalGroup(
            jPanel_acoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_acoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_acoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_novo)
                    .addComponent(jButton_editar)
                    .addComponent(jButton_Excluir)
                    .addComponent(jButton_atualizar)
                    .addComponent(jTextField_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_salvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel_inputs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_acoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(5, 5, 5))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_inputs, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jPanel_acoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_novoActionPerformed

    }//GEN-LAST:event_jButton_novoActionPerformed

    private void jButton_ExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_ExcluirMouseClicked
       
    }//GEN-LAST:event_jButton_ExcluirMouseClicked

    private void jButton_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_atualizarActionPerformed
        refreshTable();
    }//GEN-LAST:event_jButton_atualizarActionPerformed

    private void jButton_pesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_pesquisarMouseClicked
       
    }//GEN-LAST:event_jButton_pesquisarMouseClicked

    private void jButton_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salvarActionPerformed
 
    }//GEN-LAST:event_jButton_salvarActionPerformed

    private void jTable_alunosHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_jTable_alunosHierarchyChanged

    }//GEN-LAST:event_jTable_alunosHierarchyChanged

    private void jTable_alunosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable_alunosFocusGained

    }//GEN-LAST:event_jTable_alunosFocusGained

    private void jTable_alunosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTable_alunosFocusLost

    }//GEN-LAST:event_jTable_alunosFocusLost

    private void jTable_alunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_alunosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable_alunosMouseClicked

    private void jTextField_rendimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rendimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rendimentosActionPerformed

    private void jTextField_rendimentos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_rendimentos1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_rendimentos1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_atualizar;
    private javax.swing.JButton jButton_editar;
    private javax.swing.JButton jButton_novo;
    private javax.swing.JButton jButton_pesquisar;
    private javax.swing.JButton jButton_salvar;
    private javax.swing.JLabel jLabel_codAluno;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_totalRendimentos;
    private javax.swing.JLabel jLabel_totalRendimentos1;
    private javax.swing.JPanel jPanel_acoes;
    private javax.swing.JPanel jPanel_inputs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_alunos;
    private javax.swing.JTextField jTextField_codAluno;
    private javax.swing.JTextField jTextField_email1;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_pesquisar;
    private javax.swing.JTextField jTextField_rendimentos;
    private javax.swing.JTextField jTextField_rendimentos1;
    // End of variables declaration//GEN-END:variables

    public void refreshTable() {
        model.setRowCount(0);

    }
}
